spring.datasource.url=jdbc:postgresql://85.215.233.126:5432/dartshop
spring.datasource.username=main
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

token.secret.key=87nsrh8lcloqwr3qdo1fzbpmjn1jzdgrtezb8worq9dadqw5yteegj9gz46e4dyvn8
token.expirationms= 3600000

# Change before going in production
debug = true

